export const EXPERIENCE = [
  {
    companyName: "have a nice day :)",
    logo: "company1-logo.webp",
    role: "Full-stack Developer",
    position: "Full-time",
    toolsNTech: [
      "Typescript",
      "Next.js",
      "AngularJS",
      ".NET",
      "MySQL",
      "Figma",
      "WordPress",
      "Stripe",
      "Razorpay",
      "CI/CD",
      "GitHub Actions",
    ],
    description:
      "Optimized UI performance by 25% and integrated multiple payment gateways (Stripe, Razorpay, Pesapal). Automated CI/CD pipelines for streamlined deployments and maintained .NET Core local servers for backend testing. Collaborated with cross-functional teams to resolve UI/UX challenges and improve customer satisfaction.",
    joinDate: "01-12-2024",
    leaveDate: "01-04-2025",
    type: "On-Site",
  },
  {
    companyName: "but why?",
    role: "Full-stack Developer",
    logo: "company2-logo.webp",
    position: "Intern",
    toolsNTech: [
      "Typescript",
      "Next.js",
      "Hono",
      "Redis",
      "PostgreSQL",
      "Socket.io",
      "Stripe",
      "Cloudinary",
    ],
    description:
      "Co-built Claimit, a real-time auction marketplace with a team of 3. Implemented Redis caching for optimized search performance and architected a Stripe-based wallet system for secure transactions. Automated auction workflows with real-time updates and resolved concurrency issues to ensure data integrity.",
    joinDate: "01-05-2024",
    leaveDate: "01-06-2024",
    type: "On-Site",
  },
];
