export const USER = {
  fullname: "Jaimin Chovatia",
  name: "Jaimin",
  initials: "CJ",
  username: "jamnxdev",
  callLink: "https://cal.com/jamnxdev/15min",
  aboutMe: [
    "Software engineer with a product oriented mindset who knows how to ship fast.",
    "I mostly use Typescript, React, Next.js, Bun and PostgreSQL to build full stack web apps, but my skills are not limited to just these technologies. I also have experience with other technologies too.",
    "I’m not a designer, but I have a sharp eye for creating visually appealing experiences.",
  ],
  flipSentences: ["Software Engineer", "Freelancer", "Builder"],
  toolNTech: [
    { name: "C++", icon: "/tools-tech/c-plus-plus.svg" },
    { name: "HTML5", icon: "/tools-tech/html5.svg" },
    { name: "CSS3", icon: "/tools-tech/css3.svg" },
    { name: "TypeScript", icon: "/tools-tech/typescript.svg" },
    { name: "JavaScript", icon: "/tools-tech/javascript.svg" },
    { name: "Java", icon: "/tools-tech/java.svg" },
    { name: "Python", icon: "/tools-tech/python.svg" },
    { name: "React", icon: "/tools-tech/reactjs.svg" },
    { name: "Next.js", icon: "/tools-tech/nextjs.svg" },
    { name: "Node.js", icon: "/tools-tech/nodejs.svg" },
    { name: "Express.js", icon: "/tools-tech/express.svg" },
    { name: "Redis", icon: "/tools-tech/redis.svg" },
    { name: "PostgreSQL", icon: "/tools-tech/postgresql.svg" },
    { name: "MongoDB", icon: "/tools-tech/mongodb.svg" },
    { name: "Docker", icon: "/tools-tech/docker.svg" },
    { name: "Git", icon: "/tools-tech/git.svg" },
    { name: "Android", icon: "/tools-tech/android.svg" },
    { name: "Linux", icon: "/tools-tech/linux.svg" },
    { name: "Bun", icon: "/tools-tech/bunjs.svg" },
    { name: "Tailwind CSS", icon: "/tools-tech/tailwindcss.svg" },
    { name: "Prisma", icon: "/tools-tech/prisma.svg" },
    { name: "Supabase", icon: "/tools-tech/supabase.svg" },
    { name: "Figma", icon: "/tools-tech/figma.svg" },
    { name: "Postman", icon: "/tools-tech/postman.svg" },
    { name: "Socket.IO", icon: "/tools-tech/socket.io.svg" },
    { name: "Angular", icon: "/tools-tech/angular.svg" },
    { name: "AWS", icon: "/tools-tech/aws.svg" },
    { name: "Chakra UI", icon: "/tools-tech/chakraui.svg" },
    { name: "Electron", icon: "/tools-tech/electron.svg" },
    { name: "Firebase", icon: "/tools-tech/firebase.svg" },
    { name: "Heroku", icon: "/tools-tech/heroku.svg" },
    { name: "MySQL", icon: "/tools-tech/mysql.svg" },
    { name: "shadcn/ui", icon: "/tools-tech/shadcnui.svg" },
    { name: "Ubuntu", icon: "/tools-tech/ubuntu.svg" },
    { name: "Vite", icon: "/tools-tech/vitejs.svg" },
  ],
}
